import "dotenv/config";

export const {
  PORT,
  SECRET_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  NODEMAILER_USER,
  NODEMAILER_PASS,
  FRONTEND_URL,
  DATABASE_URL,
  DIRECT_URL,
} = process.env;
